-- CreateTable
CREATE TABLE "Product" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Title" TEXT,
    "Pic1" TEXT,
    "Pic2" TEXT,
    "Av" INTEGER,
    "CatId" INTEGER,
    "CatName" TEXT,
    "Lang" INTEGER,
    "Deleted" BOOLEAN NOT NULL DEFAULT false,
    "IsNew" BOOLEAN NOT NULL DEFAULT false,
    "MainId" INTEGER,
    "urlTitle" TEXT,
    "Date" TEXT,
    "Video" TEXT,
    "VideoPic" TEXT,
    "Pdf" TEXT,
    "Priority" INTEGER DEFAULT 0,
    "Code" TEXT,
    "urlTitlteCat" TEXT,
    "SEOTitle" TEXT,
    "OldLink2" TEXT,
    "OldLink" TEXT,
    "CurrentPrice" REAL,
    "CurrentOffPrice" REAL,
    "Weight" REAL,
    "TitleEn" TEXT,
    "MainName" TEXT,
    "MainUrlTitle" TEXT,
    "SubTitle" TEXT,
    "Title2" TEXT,
    "Icon" TEXT,
    "ListImageMain" TEXT,
    "ListImageOver" TEXT,
    "OverClass" TEXT,
    "SeoLead" TEXT,
    "Description" TEXT,
    "Lead" TEXT,
    "Description2" TEXT
);
